description: this is the base class to define subcategory
type: object
allOf:
  - $ref: '#/definitions/RestEntity'
  - type: object
  - title: IssueTypeBase
  - properties: 
      Code:
        type: string
      Description:
        type: string