swagger: '2.0'
info:
  $ref: ./info/index.yaml
host: api.aproplan.com
basePath: /rest
tags:
  - name: Login
    description: necessary method to identify a user
  - name: Projects
    description: Everything about the Project
  - name: Documents
    description: Everything about the Document
  - name: Points
    description: Everything about the Points
  - name: Form Template
    description: Everything about Form Templates
  - name: Forms
    description: Everything about Forms
schemes:
  - https
parameters:
  $ref: ./parameters/common.yaml
paths:
  $ref: ./paths/index.yaml
definitions: 
  $ref: ./definitions/index.yaml
